language: python
python:
  - 3.5
  - 3.4
  - 3.3
  - 2.7
sudo: false
env:
  matrix:
    - GROUP=python
matrix:
  include:
    - python: 3.5
      env: GROUP=js
cache:
  pip: true
  directories:
    - nbdime/webapp/node_modules # NPM packages
    - nbdime-web/node_modules # NPM packages
before_install:
  - pip install -U pip setuptools
  - nvm install 6
  - |
    if [[ $GROUP == python ]]; then
      pip install codecov
    elif [[ $GROUP == js ]]; then
      npm install -g codecov
    fi
install:
  - pip install --upgrade ".[test]"
before_script:
  # Set up a virtual screen for Firefox browser testing:
  - |
    if [[ $GROUP == js ]]; then
      cd nbdime-web
      export CHROME_BIN=chromium-browser
      export DISPLAY=:99.0
      sh -e /etc/init.d/xvfb start
    fi
    git config --global user.email travis@fake.com
    git config --global user.name "Travis CI"
script:
  - |
    if [[ $GROUP == python ]]; then
      py.test -l --cov-report html --cov=nbdime
    elif [[ $GROUP == js ]]; then
      npm test
    fi
before_cache:
  # Do not cache our own package
  - |
    if [[ $GROUP == js ]]; then cd ..; fi
    rm -rf nbdime/webapp/node_modules/nbdime
after_success:
    - codecov
